var canvas = document.getElementById("My_canvas");
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="blue";
ctx.lineWidth=5;
ctx.arc(250,140,50,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="black";
ctx.lineWidth=5;
ctx.arc(370,140,50,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="red";
ctx.lineWidth=5;
ctx.arc(490,140,50,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="yellow";
ctx.lineWidth=5;
ctx.arc(310,195,50,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="green";
ctx.lineWidth=5;
ctx.arc(430,195,50,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="red";
ctx.lineWidth=5;
ctx.arc(280,400,55,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="red";
ctx.lineWidth=5;
ctx.arc(460,400,55,0,2*Math.PI);
ctx.stroke();
var ctx= canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle="red";
ctx.lineWidth=5;
ctx.arc(370,495,100,0,2*Math.PI);
ctx.stroke();